### ISSUE TITLE
Le chargement d'image dans le slider de classicblocks ne fonctionne pas

### ISSUE THREAD

**Issue by nicolasalphonso** [PrestaSafe/classicblocks#7]
Bonjour,

Je souhaite créer un slider avec classicblocks 1.0.1 dans prettyblocks 2.0.2.

![image](https://github.com/PrestaSafe/classicblocks/assets/34679959/f8c114e9-4a19-463a-a1b4-53c6c3ecc6d0)

L'image chargée apparaît mais ne remplace pas l'autre. Un "check" et une croix apparaissent mais aucune action n'est possible.

**Comment by PrestaSafe** [comment]
Bonjour, que vous dit l'erreur que vous avez dans votre console javascript ? Merci de mettre en mode debug. Cordialement

**Comment by nicolasalphonso** [comment]
Bonjour, Voilà ce que j'obtiens dans la console :


![Capture d’écran 2023-07-10 084709](https://github.com/PrestaSafe/classicblocks/assets/34679959/67f3be88-4284-42e1-b7b3-a922dc022142)
![Capture d’écran 2023-07-10 084746](https://github.com/PrestaSafe/classicblocks/assets/34679959/952f5ca2-9b99-4cb7-b70f-1dfb58ae60d8)
![Capture d’écran 2023-07-10 084824](https://github.com/PrestaSafe/classicblocks/assets/34679959/7610e993-50aa-4f4f-b7b9-ba481fd614e3)

Cela répond-il à votre demande ?

Cordialement,
Nicolas

**Comment by PrestaSafe** [comment]
Bonjour, Oui je vois le problème, nous sommes en train de le fixer sur prettyblocks, il est actuellement corrigé mais nous n'avons pas encore fait la release. Le fix sera dispo cette semaine, sauf si vous utiliser prettyblocks directement depuis github, vous n'avez plus qu'a mettre à jour le repo. Cordialement

**Comment by nicolasalphonso** [comment]
Super ! Merci pour votre réponse. J'avais téléchargé la release en suivant le tuto mais je vais dorénavant utiliser le repo.
Je n'ai pas encore le niveau en PHP mais j'espère d'ici quelques mois pouvoir contribuer.

**Comment by PrestaSafe** [comment]
Ok parfait, c'est assez simple, je vais mettre à jour le readme ;)
